"use client";
import React from "react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useSearchParams } from "next/navigation";
import { Suspense } from 'react'
import Image from "next/image";

type Comment = {
  id:number,
  text: string
};

const sanitizeInput = (input: string): string => {
  // Basic sanitization: Remove tags like <script> or <>
  return input.replace(/<\/?[^>]+(>|$)/g, '');
};
const blogItem = [
  {
    id: 1,
    title: "Mountains: The Guardians of the Earth",
    date: "Sunday , 1 Jan 2023",
    content: {
      text: "Mountains are nature’s towering wonders, standing as a testament to Earth's history and power. These ecosystems, home to unique wildlife like snow leopards and alpine flowers, also serve as vital water sources, providing life to billions. Formed by tectonic movements or volcanic eruptions, mountains like the Himalayas and Rockies inspire awe and adventure. Culturally, mountains hold spiritual significance, revered in religions and celebrated in art and literature. They are often seen as places of solace and introspection, drawing adventurers and pilgrims alike. Yet, challenges like climate change and deforestation threaten their ecosystems. Fragile mountain habitats require dedicated conservation efforts to maintain biodiversity. Sustainable tourism and responsible mountaineering practices play a key role in preserving these natural wonders. Modern initiatives focus on balancing human activity with environmental protection. By celebrating their grandeur while respecting their fragility, we can ensure mountains remain majestic for generations to come.",
       image : "/1blog.jpg",
       alt : "Majestic Mountains"
    }
  },
  {
    id : 2 ,
    title: "Rivers: The Lifeblood of Nature",
    date: "Sunday , 1 Jan 2023",
    content: {
      text : "Rivers are Earth’s arteries, weaving through landscapes and bringing life wherever they flow. From the mighty Amazon to the serene Ganges, rivers support diverse ecosystems and communities. They are vital for drinking water, agriculture, and transportation.Beyond their practical uses, rivers inspire myths, art, and spirituality. They often serve as symbols of renewal and continuity in cultural traditions. However, pollution and climate change pose significant threats, endangering aquatic life and human livelihoods. Industrial waste and plastic pollution heavily impact river health.By advocating for cleaner practices and sustainable management, we can ensure rivers remain a source of life and wonder. Community-led river cleanup drives and international agreements on water conservation are steps in the right direction. Protecting rivers safeguards not only their beauty but also the well-being of those who depend on them.",
      image : "/2blog.jpg",
      alt : "River"
    }
  },

  {
    id: 3 ,
    title : "Enchanting Forests: Nature’s Green Lungs",
    date: "Sunday , 1 Jan 2023",
    content : {
      text: "Forests are the verdant heart of our planet, offering shelter to countless species and absorbing carbon dioxide to regulate the climate. From the dense Amazon rainforest to serene pine woods, forests captivate with their diversity and beauty.They are sources of food, medicine, and inspiration, yet face threats from deforestation and illegal logging. Forests also play a crucial role in preventing soil erosion and maintaining water cycles. Conservation efforts, reforestation projects, and eco-tourism can help preserve these vital ecosystems for future generations.Additionally, engaging local communities in sustainable forestry practices ensures a balance between development and preservation. Forests serve as living classrooms, teaching us about interconnectedness and resilience. Their protection is essential for combating climate change and maintaining Earth’s biodiversity.",
      image : "/3blog.jpg",
      alt : "Enchanting Forests"
    }
  },

  {
    id : 4,
    title : "The Ocean’s Mysteries: A Vast Blue World",
    date: "Sunday , 1 Jan 2023",
    content: {
      text: "Covering 70% of Earth’s surface, oceans are teeming with life, from vibrant coral reefs to mysterious deep-sea creatures. They regulate the planet’s climate, provide food, and support millions of livelihoods. Oceans are also a major source of oxygen, generated by phytoplankton.However, overfishing, plastic pollution, and warming temperatures threaten marine life. Coral bleaching, caused by rising sea temperatures, endangers vibrant underwater ecosystems. Protecting our oceans through marine reserves, reducing plastic use, and supporting sustainable fishing practices is crucial to maintaining their health and beauty.Oceans also hold untapped potential for renewable energy, such as wave and tidal power. Raising awareness about their importance inspires collective action. Whether it’s participating in beach cleanups or advocating for policy changes, every effort counts in preserving this vast blue world.",
      image : "/4blog.jpg" ,
      alt : "Ocean"
    }
  },

  {
    id: 5,
    title: "The Vital Role of Grasslands",
    date: "Friday , 23 Dec 2023",
    content: {
      text:"Grasslands, often overlooked, are vital ecosystems that support unique wildlife like bison and antelopes. These vast open spaces, such as the African savannas and North American prairies, are crucial for agriculture and carbon storage. Grasslands also provide grazing areas for livestock, contributing to food security.Overgrazing and habitat loss, however, threaten their balance. Invasive species and urban development further disrupt these ecosystems. Sustainable farming and conservation initiatives are essential to ensure grasslands continue to thrive and support biodiversity.Promoting education about the importance of grasslands can inspire community-driven conservation efforts. Grasslands are also essential for preventing desertification, acting as buffers in arid regions. Their preservation ensures the survival of iconic species and maintains ecological harmony.",
      image :"/5blog.jpg",
      alt :" Grassland"
    }
  },

  {
    id : 6,
    title: "The Frozen Realms of Glaciers",
    date : "Monday , 14 May 2023",
    content: {
      text: "Glaciers are majestic reservoirs of freshwater, slowly carving the landscape as they move. Found in polar regions and high mountains, they feed rivers and sustain ecosystems downstream. Glaciers also act as natural climate regulators, reflecting sunlight to maintain Earth’s temperature balance.Climate change accelerates their melting, threatening water supplies and raising sea levels. This loss not only endangers habitats but also communities relying on glacial meltwater for survival. Global efforts to reduce emissions and protect these icy giants are imperative for future generations.Scientific studies of glaciers provide insights into past climate conditions, helping predict future trends. Public awareness campaigns and eco-friendly policies are critical to slowing glacial retreat. Protecting glaciers safeguards a vital resource and preserves natural beauty.",
      image: "/6blog.jpg",
      alt: "The Frozen Glaciers"
    }
  },

  {
    id : 7,
    title: " The Desert’s Hidden Life",
    date:"Tuesday , 5 Jun 2023 ",
    content: {
      text: "Deserts, though arid and harsh, are home to unique plants and animals adapted to survive extreme conditions. The Sahara, Mojave, and Gobi showcase nature’s resilience and beauty. Desert flora, like cacti, and fauna, such as camels and foxes, display remarkable adaptations.Threats like desertification and climate change endanger these fragile ecosystems. Expanding agriculture and water mismanagement exacerbate the issue. Sustainable land management and education about desert conservation can help preserve these unique landscapes.Deserts also offer opportunities for renewable energy projects, such as solar farms. Their stark beauty inspires art and tourism, encouraging sustainable interaction with these environments. Preserving deserts ensures their biodiversity and their role in Earth’s ecological balance.",
      image: "/7blog.jpg",
      alt: "Desert"
    } 
  },


  {
    id : 8,
    title: "The Importance of Wetlands",
    date: "Wednesday , 7 Jul 2022",
    content: {
      text: "Wetlands, such as marshes and swamps, are nature’s filters, cleaning water and providing habitats for diverse species. They also act as buffers, protecting against floods and storm surges. Wetlands store carbon, helping mitigate climate change.Human activity, however, is draining and polluting wetlands at an alarming rate. Agricultural expansion and urbanization are major threats. Protecting and restoring these areas is essential to maintain their ecological and economic benefits.Community involvement in wetland conservation fosters a deeper understanding of their value. Wetlands also serve as vital breeding grounds for birds and aquatic life. By preserving them, we protect a wealth of biodiversity and natural resources.",
      image: "/8blog.jpg",
      alt: "Wetland"
    }
  },
   
  {
    id : 9,
    title: "The Role of Trees in Our Ecosystem",
    date: "Saturday , 7 Feb 2022",
    content:{
      text:"Trees are Earth’s silent workers, providing oxygen, reducing carbon dioxide, and supporting countless species. From mighty oaks to towering redwoods, they are essential for our planet’s health. Trees also prevent soil erosion and provide shade, reducing urban heat.Deforestation and urbanization threaten forests worldwide. Industrial expansion and unsustainable agriculture compound the issue. Planting trees, supporting sustainable forestry, and spreading awareness can ensure their survival for generations to come.Initiatives like urban tree planting projects and forest preservation campaigns are making a difference. Trees are symbols of life and growth, reminding us of our responsibility to care for nature. Their conservation ensures a healthier, greener future.",
      image: "/9blog.jpg",
      alt: "Ecosystem"
    }
  },

  {
    id: 10,
    title: "The Beauty of Flowering Meadows",
    date: "Thursday , 12 Nov 2021",
    content: {
      text: "Flowering meadows are vibrant ecosystems filled with diverse plant and insect species. They are not only visually stunning but also critical for pollinators like bees and butterflies. Meadows support agricultural productivity by enhancing pollination.Agricultural expansion and climate change threaten these habitats. Overuse of pesticides and habitat fragmentation also impact meadow health. Promoting wildflower planting and preserving natural meadows can protect these essential landscapes and their inhabitants.Flowering meadows inspire artists and nature lovers, offering tranquil spaces for recreation. Their conservation supports ecological balance and biodiversity. Efforts to protect them ensure the survival of pollinators and the beauty of these vibrant landscapes.",
      image:"/10blog.jpg",
      alt: "Flowering Meadows"
    }
  }

  

];

const Blog = () => {
  const route = useRouter();
  const searchId = useSearchParams();
  const id = searchId.get('id');
  const [isComment ,setIsComment] = useState<Comment[]>([]);
  const [newComment ,setNewComment] = useState("")

  

  if (id){
    const blogPost = blogItem.find((post) => post.id === Number(id));
    if(blogPost){
      return(
        <div className="flex flex-col items-center justify-center mt-16 gap-4">
          <div className="flex flex-col gap-3 ">
          <Image src={blogPost.content.image} alt={blogPost.content.alt} width={400} height={250} className=" rounded-xl sm:w-[600px] sm:h-[400px] lg:w-[1000px] lg:h-[300px] xl:w-[1100px] xl:h-[500px]"/>
         
          <h1 className="text-[#6941C6] font-semibold text-[18px] self-start">{blogPost.date}</h1>
          <h1 className="font-medium">{blogPost.title}</h1>
          </div>
          <p className=" text-justify text-[#667085] mx-5">{blogPost.content.text}</p>
         


          <div className="w-full max-w-2xl mt-6">
            <h2 className="font-semibold text-xl mb-4">Comments</h2>
            <div className="flex gap-4 mb-4">
              <input
                type="text"
                value={newComment}
                onChange={(e) => setNewComment(e.target.value)}
                placeholder="Write a comment..."
                className="flex-1 px-4 py-2 border rounded-md text-[#C11574]"
              />
              <Suspense>
              <button
                onClick={() => {
                  const sanitizedComment = sanitizeInput(newComment);
                  if (sanitizedComment.trim()) {
                    setIsComment([
                      ...isComment,
                      { id: isComment.length + 1, text: sanitizedComment },
                    ]);
                    setNewComment('');
                  }
                }}
                className="px-4 py-2 bg-[#6941C6] text-white rounded-md"
              >
                Add Comment
              </button>
              </Suspense>
            </div>
            <Suspense>
            <ul className="space-y-2">
              {isComment.map((comment) => (
                <li
                  key={comment.id}
                  className="p-2 border rounded-md bg-[#F9F5FF] text-[#6941C6]"
                >
                  {comment.text}
                </li>
              ))}
            </ul>
            </Suspense>
          </div>
          <button onClick={()=>route.push("/")} className="flex  h-[30px] w-[200px] bg-[#F9F5FF] text-[#C11574] rounded-3xl  items-center justify-center self-center my-10">Back to Home Page </button>
        </div>
      )
    } 
    else {
      return (
        <div>
        <div>Blog not found</div>
        <button onClick={()=>route.push("/")}  className="flex self-start h-[30px] w-[200px] bg-[#F9F5FF] text-[#6941C6] rounded-3xl  items-center justify-center">Back to Home Page </button>
        </div>
      )
    }

  }


  return (
    <div>
      <h1 className="font-bold flex text-[24px] my-10 ml-4">Recent blog post </h1>
      <div className="  grid sm:grid-cols-2 gap-10 lg:grid-cols-3">
        {blogItem.map((post)=>(
          <div className="flex flex-col gap-[10px] items-center">
          <div key={post.id} className="flex flex-col gap-[10px] ">
           
            <Image src={post.content.image} alt={post.content.alt} width={350} height={200} className=" rounded-xl sm:w-[400px] sm:h-[300px]"/>
            <p className="text-[#6941C6] font-semibold text-[14px] ">{post.date}</p>
              <h2 className="font-medium">{post.title}</h2>
              <p className=" line-clamp-3 text-[#667085] h-[80px] text-justify w-[350px]">{post.content.text}</p>
              <Suspense>
              <button  onClick={() => route.push(`/?id=${post.id}`)}
              style={{ cursor: 'pointer' }} className="flex self-start h-[30px] w-[100px] bg-[#F9F5FF] text-[#6941C6] rounded-3xl  items-center justify-center">Open post</button>
              </Suspense>
             
          </div>
          </div>
        )
          
        )}
      </div>
    </div>
  ) ;
};

export default Blog;
